CFLAGS =
CFLAGS += -g
CFLAGS += -O3
CFLAGS += -Wall
CFLAGS += --std=c99
CFLAGS += -Wno-unused-function
CFLAGS += -fno-inline
CFLAGS += -I..

all: perftest

clean:
	rm -fr perftest.o perftest perftest.dSYM
